function lab18 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LAB18 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  LAB18 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  lab18 = importfile("C:\Users\nide0150\Desktop\lab1_8.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Sep-2019 11:12:33

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Timesec", "Pressurepsi", "TopofTopC", "BottomofTopC", "TopofBottomC", "BottomofBottomC", "CurrentA", "OptSwitch", "PM"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 9, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 9, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
lab18 = readtable(filename, opts);

end